#!/usr/bin/env bash
Java_PluginPath="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin"
Java_BundleVendor=$( /usr/bin/defaults read "${Java_PluginPath}/Contents/Info" CFBundleIdentifier 2>/dev/null )
Java_BundleVersionString=$( /usr/bin/defaults read "${Java_PluginPath}/Contents/Info" CFBundleShortVersionString 2>/dev/null )
Java_BlundleVersion=$( /usr/bin/defaults read "${Java_PluginPath}/Contents/Info" CFBundleVersion 2>/dev/null )

if [[ -e "${Java_PluginPath}" ]]; then
    if [ "$Java_BundleVendor" = "com.oracle.java.JavaAppletPlugin" ]; then
            JavaVendor=Oracle
    elif [ "$Java_BundleVendor" = "com.apple.java.JavaAppletPlugin" ]; then
            JavaVendor=Apple
    fi
    echo "${Java_BundleVersionString} ($JavaVendor ${Java_BlundleVersion})"
else
    echo "Java is not installed"
fi
